sonar.projectKey=devtrack
sonar.projectName=DevTrack
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests

sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=node_modules/**,coverage/**

sonar.sourceEncoding=UTF-8
