apiVersion: apps/v1
kind: Deployment
metadata:
  name: devtrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devtrack
  template:
    metadata:
      labels:
        app: devtrack
    spec:
      containers:
        - name: devtrack
          image: devtrack:14
          imagePullPolicy: Never
          ports:
            - containerPort: 3000